// AUTO-GENERATED. Do not edit manually.
// Sorted by (left, right) poker strength: weak → strong.

export const HAND_CATEGORIES = [
  "highCardVsCardChop",
  "highCardVsHighCardKickerDecides",
  "highCardVsLowerCard",
  "pairVsHighCard",
  "pairVsLowerPair",
  "pairVsLowerPairChop",
  "pairVsPairKickerDecides",
  "twoPairVsHighCard",
  "twoPairVsPair",
  "twoPairVsLowerTwoPair",
  "twoPairVsTwoPairChop",
  "twoPairVsTwoPairKickerDecides",
  "threeOfAKindVsHighCard",
  "threeOfAKindVsPair",
  "threeOfAKindVsTwoPair",
  "threeOfAKindVsLowerThreeOfAKind",
  "threeOfAKindVsThreeOfAKindChop",
  "threeOfAKindVsThreeOfAKindKickerDecides",
  "straightVsHighCard",
  "straightVsPair",
  "straightVsTwoPair",
  "straightVsThreeOfAKind",
  "straightVsLowerStraight",
  "straightVsStraightChop",
  "flushVsHighCard",
  "flushVsPair",
  "flushVsTwoPair",
  "flushVsThreeOfAKind",
  "flushVsStraight",
  "flushVsFlushChop",
  "flushVsLowerFlush",
  "fullHouseVsPair",
  "fullHouseVsTwoPair",
  "fullHouseVsThreeOfAKind",
  "fullHouseVsStraight",
  "fullHouseVsFlush",
  "fullHouseVsFullHouseChop",
  "fullHouseVsLowerFullHouse",
  "fourOfAKindVsPair",
  "fourOfAKindVsTwoPair",
  "fourOfAKindVsThreeOfAKind",
  "fourOfAKindVsStraight",
  "fourOfAKindVsFlush",
  "fourOfAKindVsFullHouse",
  "fourOfAKindVsFourOfAKindChop",
  "fourOfAKindVsFourOfAKindKickerDecides",
  "fourOfAKindVsLowerFourOfAKind",
  "straightFlushVsHighCard",
  "straightFlushVsPair",
  "straightFlushVsTwoPair",
  "straightFlushVsThreeOfAKind",
  "straightFlushVsStraight",
  "straightFlushVsFlush",
  "straightFlushVsFullHouse",
  "straightFlushVsFourOfAKind",
  "straightFlushVsStraightFlushChop",
  "straightFlushVsStraightFlushKickerDecides"
] as const;
export type HandCategory = typeof HAND_CATEGORIES[number];

export const HAND_CATEGORY_COUNTS: Record<HandCategory, number> = {
  "highCardVsCardChop": 100,
  "highCardVsHighCardKickerDecides": 100,
  "highCardVsLowerCard": 100,
  "pairVsHighCard": 100,
  "pairVsLowerPair": 100,
  "pairVsLowerPairChop": 100,
  "pairVsPairKickerDecides": 100,
  "twoPairVsHighCard": 100,
  "twoPairVsPair": 100,
  "twoPairVsLowerTwoPair": 100,
  "twoPairVsTwoPairChop": 100,
  "twoPairVsTwoPairKickerDecides": 100,
  "threeOfAKindVsHighCard": 100,
  "threeOfAKindVsPair": 100,
  "threeOfAKindVsTwoPair": 100,
  "threeOfAKindVsLowerThreeOfAKind": 100,
  "threeOfAKindVsThreeOfAKindChop": 100,
  "threeOfAKindVsThreeOfAKindKickerDecides": 100,
  "straightVsHighCard": 100,
  "straightVsPair": 100,
  "straightVsTwoPair": 100,
  "straightVsThreeOfAKind": 100,
  "straightVsLowerStraight": 100,
  "straightVsStraightChop": 100,
  "flushVsHighCard": 100,
  "flushVsPair": 100,
  "flushVsTwoPair": 100,
  "flushVsThreeOfAKind": 100,
  "flushVsStraight": 100,
  "flushVsFlushChop": 100,
  "flushVsLowerFlush": 100,
  "fullHouseVsPair": 100,
  "fullHouseVsTwoPair": 100,
  "fullHouseVsThreeOfAKind": 100,
  "fullHouseVsStraight": 100,
  "fullHouseVsFlush": 100,
  "fullHouseVsFullHouseChop": 100,
  "fullHouseVsLowerFullHouse": 100,
  "fourOfAKindVsPair": 100,
  "fourOfAKindVsTwoPair": 100,
  "fourOfAKindVsThreeOfAKind": 100,
  "fourOfAKindVsStraight": 71,
  "fourOfAKindVsFlush": 100,
  "fourOfAKindVsFullHouse": 100,
  "fourOfAKindVsFourOfAKindChop": 100,
  "fourOfAKindVsFourOfAKindKickerDecides": 100,
  "fourOfAKindVsLowerFourOfAKind": 2,
  "straightFlushVsHighCard": 100,
  "straightFlushVsPair": 100,
  "straightFlushVsTwoPair": 100,
  "straightFlushVsThreeOfAKind": 50,
  "straightFlushVsStraight": 100,
  "straightFlushVsFlush": 100,
  "straightFlushVsFullHouse": 27,
  "straightFlushVsFourOfAKind": 1,
  "straightFlushVsStraightFlushChop": 44,
  "straightFlushVsStraightFlushKickerDecides": 10
};

export const TOTAL_CATEGORIES = 57;
export const TOTAL_HANDS = 5205;
